from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.regression_runner import RegressionCase, run_regression_cli

HOTEL_REGRESSION_CASES: list[RegressionCase] = [
    # reservation — 訂房
    RegressionCase("reservation", "我要訂房。", "我欲訂房。"),
    RegressionCase("reservation", "請問有空房嗎？", "借問有閒房無？"),
    RegressionCase("reservation", "一晚多少錢？", "一晚偌濟錢？"),
    RegressionCase("reservation", "我要住兩晚。", "我欲住兩晚。"),
    RegressionCase("reservation", "我要住單人房。", "我欲住單人房。"),
    RegressionCase("reservation", "我想改訂房日期。", "我想欲改訂房日期。"),
    RegressionCase("reservation", "我需要改訂房日期。", "我欲改訂房日期。"),
    RegressionCase("reservation", "請協助改訂房日期。", "請鬥相共改訂房日期。"),
    RegressionCase("reservation", "我想改預約日期。", "我想欲改預約日期。"),
    RegressionCase("reservation", "可以幫我改預約日期嗎？", "會當替我改預約日期無？"),
    RegressionCase("reservation", "我想取消訂房。", "我想欲取消訂房。"),
    RegressionCase("reservation", "我需要取消訂房。", "我欲取消訂房。"),
    RegressionCase("reservation", "可以幫我取消訂房嗎？", "會當替我取消訂房無？"),
    RegressionCase("reservation", "請協助取消訂房。", "請鬥相共取消訂房。"),
    RegressionCase("reservation", "我想取消住宿。", "我想欲取消歇暝。"),
    RegressionCase("reservation", "我需要取消住宿。", "我欲取消歇暝。"),
    RegressionCase("reservation", "可以幫我取消住宿嗎？", "會當替我取消歇暝無？"),
    RegressionCase("reservation", "請協助取消住宿。", "請鬥相共取消歇暝。"),
    RegressionCase("reservation", "請協助取消預約。", "請鬥相共取消預約。"),
    RegressionCase("reservation", "可以幫我查房價嗎？", "會當替我查房價無？"),
    RegressionCase("reservation", "我需要查房價。", "我欲查房價。"),
    RegressionCase("reservation", "我需要查訂房紀錄。", "我欲查訂房紀錄。"),
    RegressionCase("reservation", "請協助查訂房紀錄。", "請鬥相共查訂房紀錄。"),
    RegressionCase("reservation", "我需要確認訂房紀錄。", "我欲確認訂房紀錄。"),
    RegressionCase("reservation", "我想確認訂房紀錄。", "我想欲確認訂房紀錄。"),
    RegressionCase("reservation", "可以幫我確認訂房紀錄嗎？", "會當替我確認訂房紀錄無？"),
    RegressionCase("reservation", "請幫我確認訂房紀錄。", "請替我確認訂房紀錄。"),
    RegressionCase("reservation", "麻煩你幫我確認訂房紀錄。", "麻煩你替我確認訂房紀錄。"),
    RegressionCase("reservation", "幫我確認訂房紀錄。", "替我確認訂房紀錄。"),
    RegressionCase("reservation", "請協助確認訂房紀錄。", "請鬥相共確認訂房紀錄。"),
    RegressionCase("reservation", "可以加床嗎？", "會當加床無？"),
    RegressionCase("reservation", "訂房有含早餐嗎？", "訂房有含早頓無？"),
    RegressionCase("reservation", "入住人數要改。", "入住人數愛改。"),
    RegressionCase("reservation", "可以取消訂房嗎？", "會當取消訂房無？"),
    RegressionCase("reservation", "我想改入住時間。", "我想欲改入住時間。"),
    RegressionCase("reservation", "可以幫我改住宿天數嗎？", "會當替我改歇暝天數無？"),
    RegressionCase("reservation", "我需要改住宿天數。", "我欲改歇暝天數。"),
    RegressionCase("reservation", "我想改房型。", "我想欲改房型。"),
    RegressionCase("reservation", "可以幫我改入住人數嗎？", "會當替我改入住人數無？"),
    RegressionCase("reservation", "我想改加床數量。", "我想欲改加床數量。"),
    RegressionCase("reservation", "可以幫我查加床費用嗎？", "會當替我查加床費用無？"),
    RegressionCase("reservation", "我想改退房日期。", "我想欲改退房日期。"),
    # check_in — 入住
    RegressionCase("check_in", "幾點可以入住？", "幾點會當入住？"),
    RegressionCase("check_in", "可以提早入住嗎？", "會當較早入住無？"),
    RegressionCase("check_in", "行李可以先寄放嗎？", "行李會當先寄放無？"),
    RegressionCase("check_in", "請問有停車場嗎？", "借問有停車場無？"),
    RegressionCase("check_in", "我會晚一點到。", "我會較晏一點到。"),
    RegressionCase("check_in", "入住需要證件嗎？", "入住需要證件無？"),
    RegressionCase("check_in", "需要押金嗎？", "需要押金無？"),
    RegressionCase("check_in", "房號是多少？", "房號是幾號？"),
    RegressionCase("check_in", "可以幫我保管行李嗎？", "會當替我保管行李無？"),
    RegressionCase("check_in", "可以幫我查入住紀錄嗎？", "會當替我查入住紀錄無？"),
    RegressionCase("check_in", "可以幫我換停車位嗎？", "會當替我換停車位無？"),
    RegressionCase("check_in", "可以幫我查停車費嗎？", "會當替我查停車費無？"),
    RegressionCase("check_in", "可以幫我查停車場位置嗎？", "會當替我查停車場位置無？"),
    RegressionCase("check_in", "可以幫我查房卡押金嗎？", "會當替我查房卡押金無？"),
    RegressionCase("check_in", "可以幫我查停車位位置嗎？", "會當替我查停車位位置無？"),
    RegressionCase("check_in", "可以幫我查停車場費用嗎？", "會當替我查停車場費用無？"),
    RegressionCase("check_in", "是否方便請您幫我換房？", "敢方便請你替我換房？"),
    # check_out — 退房
    RegressionCase("check_out", "幾點要退房？", "幾點愛退房？"),
    RegressionCase("check_out", "我要退房。", "我欲退房。"),
    RegressionCase("check_out", "可以延後退房嗎？", "會當較晏退房無？"),
    RegressionCase("check_out", "退房後可以寄放行李嗎？", "退房後會當寄放行李無？"),
    RegressionCase("check_out", "請幫我開收據。", "請共我開收據。"),
    RegressionCase("check_out", "可以幫我印收據嗎？", "會當替我印收據無？"),
    RegressionCase("check_out", "房卡要交回櫃檯嗎？", "房卡愛交轉去櫃檯無？"),
    RegressionCase("check_out", "可以晚一點退房嗎？", "會當較晏一點退房無？"),
    RegressionCase("check_out", "房卡要交回哪裡？", "房卡愛交轉去佗位？"),
    RegressionCase("check_out", "可以幫我叫車嗎？", "會當替我叫車無？"),
    RegressionCase("check_out", "我想晚一點退房。", "我想欲較晏一點退房。"),
    RegressionCase("check_out", "我想改退房時間。", "我想欲改退房時間。"),
    RegressionCase("check_out", "可以幫我叫計程車嗎？", "會當替我叫計程車無？"),
    RegressionCase("check_out", "可以幫我查退房時間嗎？", "會當替我查退房時間無？"),
    RegressionCase("check_out", "可以幫我查退房紀錄嗎？", "會當替我查退房紀錄無？"),
    # amenities — 設施服務
    RegressionCase("amenities", "請問有早餐嗎？", "借問有早頓無？"),
    RegressionCase("amenities", "早餐在哪裡？", "早頓佇佗位？"),
    RegressionCase("amenities", "請問有游泳池嗎？", "借問有泅水池無？"),
    RegressionCase("amenities", "請問有吹風機嗎？", "借問有吹風機無？"),
    RegressionCase("amenities", "請問有洗衣服務嗎？", "借問有洗衫服務無？"),
    RegressionCase("amenities", "請問有健身房嗎？", "借問有健身房無？"),
    RegressionCase("amenities", "請問有洗衣機嗎？", "借問有洗衣機無？"),
    RegressionCase("amenities", "房間有wifi嗎？", "房間有wifi無？"),
    RegressionCase("amenities", "可以多給我一雙拖鞋嗎？", "會當加予我一雙淺拖仔無？"),
    RegressionCase("amenities", "有牙刷嗎？", "有齒抿仔無？"),
    RegressionCase("amenities", "早餐幾點開始？", "早頓幾點開始？"),
    RegressionCase("amenities", "房間要打掃嗎？", "房間愛拚掃無？"),
    RegressionCase("amenities", "我想加一條棉被。", "我想欲加一領棉被。"),
    RegressionCase("amenities", "可以幫我補毛巾嗎？", "會當替我補面巾無？"),
    RegressionCase("amenities", "可以幫我補牙刷嗎？", "會當替我補齒抿仔無？"),
    RegressionCase("amenities", "可以幫我換枕頭嗎？", "會當替我換枕頭無？"),
    RegressionCase("amenities", "可以幫我換浴巾嗎？", "會當替我換浴巾無？"),
    RegressionCase("amenities", "可以幫我叫客房服務嗎？", "會當替我叫客房服務無？"),
    RegressionCase("amenities", "可以幫我換房卡嗎？", "會當替我換房卡無？"),
    RegressionCase("amenities", "可以協助我換房卡嗎？", "會當鬥相共我換房卡無？"),
    RegressionCase("amenities", "我需要換房卡。", "我欲換房卡。"),
    RegressionCase("amenities", "請協助換房卡。", "請鬥相共換房卡。"),
    RegressionCase("amenities", "可以幫我加早餐嗎？", "會當替我加早頓無？"),
    RegressionCase("amenities", "我想改早餐時間。", "我想欲改早頓時間。"),
    RegressionCase("amenities", "可以幫我查早餐時間嗎？", "會當替我查早頓時間無？"),
    RegressionCase("amenities", "可以幫我查房間設備嗎？", "會當替我查房間設備無？"),
    RegressionCase("amenities", "可以幫我查洗衣時間嗎？", "會當替我查洗衫時間無？"),
    RegressionCase("amenities", "可以幫我查房務時間嗎？", "會當替我查房務時間無？"),
    RegressionCase("amenities", "可以幫我查早餐券嗎？", "會當替我查早頓券無？"),
    RegressionCase("amenities", "可以幫我查電梯位置嗎？", "會當替我查電梯位置無？"),
    RegressionCase("amenities", "可以幫我查早餐地點嗎？", "會當替我查早頓地點無？"),
    # issues — 問題反映
    RegressionCase("issues", "房間太吵了。", "房間太吵矣。"),
    RegressionCase("issues", "冷氣壞了。", "冷氣歹去矣。"),
    RegressionCase("issues", "熱水沒有了。", "熱水無矣。"),
    RegressionCase("issues", "房卡打不開房門。", "房卡開袂開房門。"),
    RegressionCase("issues", "房間的網路不能用。", "房間的網路袂當用。"),
    RegressionCase("issues", "房間漏水。", "房間漏水。"),
    RegressionCase("issues", "房間沒有毛巾。", "房間無面巾。"),
    RegressionCase("issues", "可以幫我換房嗎？", "會當替我換房無？"),
    RegressionCase("issues", "可以幫我們換房嗎？", "會當替阮換房無？"),
    RegressionCase("issues", "可以幫你們換房嗎？", "會當替恁換房無？"),
    RegressionCase("issues", "可以幫他們換房嗎？", "會當替怹換房無？"),
    RegressionCase("issues", "可以幫大家換房嗎？", "會當替逐家換房無？"),
    RegressionCase("issues", "可以幫各位換房嗎？", "會當替逐家換房無？"),
    RegressionCase("issues", "可以幫客人換房嗎？", "會當替人客換房無？"),
    RegressionCase("issues", "可以幫病人換房嗎？", "會當替病人換房無？"),
    RegressionCase("issues", "可以幫家屬換房嗎？", "會當替家屬換房無？"),
    RegressionCase("issues", "可不可以幫你們換房？", "敢會當替恁換房？"),
    RegressionCase("issues", "可不可以幫他們換房？", "敢會當替怹換房？"),
    RegressionCase("issues", "可不可以幫大家換房？", "敢會當替逐家換房？"),
    RegressionCase("issues", "可不可以幫各位換房？", "敢會當替逐家換房？"),
    RegressionCase("issues", "可不可以幫客人換房？", "敢會當替人客換房？"),
    RegressionCase("issues", "可不可以幫病人換房？", "敢會當替病人換房？"),
    RegressionCase("issues", "可不可以幫家屬換房？", "敢會當替家屬換房？"),
    RegressionCase("issues", "我需要換房。", "我欲換房。"),
    RegressionCase("issues", "請協助換房。", "請鬥相共換房。"),
    RegressionCase("issues", "是否可以協助我換房？", "敢會當鬥相共我換房？"),
    RegressionCase("issues", "是否可以請您協助我換房？", "敢會當請你鬥相共我換房？"),
    RegressionCase("issues", "是否可以請您協助我們換房？", "敢會當請你鬥相共阮換房？"),
    RegressionCase("issues", "是否可以協助你們換房？", "敢會當鬥相共恁換房？"),
    RegressionCase("issues", "是否可以協助他們換房？", "敢會當鬥相共怹換房？"),
    RegressionCase("issues", "是否可以協助大家換房？", "敢會當鬥相共逐家換房？"),
    RegressionCase("issues", "是否可以協助各位換房？", "敢會當鬥相共逐家換房？"),
    RegressionCase("issues", "是否可以協助客人換房？", "敢會當鬥相共人客換房？"),
    RegressionCase("issues", "是否可以協助病人換房？", "敢會當鬥相共病人換房？"),
    RegressionCase("issues", "是否可以協助家屬換房？", "敢會當鬥相共家屬換房？"),
    RegressionCase("issues", "是否方便協助我換房？", "敢方便鬥相共我換房？"),
    RegressionCase("issues", "是否方便協助我們換房？", "敢方便鬥相共阮換房？"),
    RegressionCase("issues", "麻煩你幫我換房。", "麻煩你替我換房。"),
    RegressionCase("issues", "請您幫我換房。", "請你替我換房。"),
    RegressionCase("issues", "可不可以請您幫我換房？", "敢會當請你替我換房？"),
    RegressionCase("issues", "可不可以請您幫我們換房？", "敢會當請你替阮換房？"),
    RegressionCase("issues", "能請您幫我換房嗎？", "會當請你替我換房無？"),
    RegressionCase("issues", "是否能請您幫我換房？", "敢會當請你替我換房？"),
    RegressionCase("issues", "方便請您幫我換房嗎？", "方便請你替我換房無？"),
    RegressionCase("issues", "可以麻煩您幫我換房嗎？", "會當麻煩你替我換房無？"),
    RegressionCase("issues", "可以麻煩您幫我們換房嗎？", "會當麻煩你替阮換房無？"),
    RegressionCase("issues", "可以麻煩您協助我換房嗎？", "會當麻煩你鬥相共我換房無？"),
    RegressionCase("issues", "可以麻煩您協助我們換房嗎？", "會當麻煩你鬥相共阮換房無？"),
    RegressionCase("issues", "拜託您幫我換房。", "拜託你替我換房。"),
    RegressionCase("issues", "拜託您幫我們換房。", "拜託你替阮換房。"),
    RegressionCase("issues", "我想請您幫我換房。", "我想欲請你替我換房。"),
    RegressionCase("issues", "遙控器壞了。", "遙控器歹去矣。"),
    RegressionCase("issues", "房間太冷了。", "房間太寒矣。"),
    RegressionCase("issues", "可以換安靜一點的房間嗎？", "會當換較恬的房間無？"),
    RegressionCase("issues", "可以幫我修冷氣嗎？", "會當替我修空調無？"),
    RegressionCase("issues", "房間可以不要打掃嗎？", "房間會當免拚掃無？"),
    RegressionCase("issues", "房間可以晚一點打掃嗎？", "房間會當較晏一點拚掃無？"),
    RegressionCase("issues", "可以幫我換房型嗎？", "會當替我換房型無？"),
    RegressionCase("issues", "我需要換房型。", "我欲換房型。"),
    RegressionCase("issues", "可以幫我叫清潔人員嗎？", "會當替我叫清潔人員無？"),
    RegressionCase("issues", "可以幫旅客換房嗎？", "會當替旅客換房無？"),
    RegressionCase("issues", "可不可以幫旅客換房？", "敢會當替旅客換房？"),
    RegressionCase("issues", "請協助旅客換房。", "請鬥相共旅客換房。"),
    RegressionCase("issues", "可以幫住客換房嗎？", "會當替住客換房無？"),
    RegressionCase("issues", "可不可以幫住客換房？", "敢會當替住客換房？"),
    RegressionCase("issues", "請協助住客換房。", "請鬥相共住客換房。"),
]


def main() -> int:
    return run_regression_cli(
        HOTEL_REGRESSION_CASES,
        description='飯店住宿情境 regression runner',
    )


if __name__ == "__main__":
    raise SystemExit(main())
