from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.regression_runner import RegressionCase, run_regression_cli

TRANSPORT_REGRESSION_CASES: list[RegressionCase] = [
    # shuttle / transfer
    RegressionCase("shuttle_transfer", "請問往火車站的接駁車在哪裡搭？", "借問往火車頭的接駁車佇佗位搭？"),
    RegressionCase("shuttle_transfer", "高鐵接駁車在對面站牌搭。", "高鐵接駁車佇對面站牌搭。"),
    RegressionCase("shuttle_transfer", "這班高鐵接駁車今天改到對面站牌上車。", "這班高鐵接駁車今仔日改去對面站牌上車。"),
    RegressionCase("shuttle_transfer", "這班車有到火車站後站嗎？", "這班車有到火車頭後站無？"),
    RegressionCase("shuttle_transfer", "如果你趕時間，建議你改搭計程車去高鐵站。", "若是你趕時間，建議你改坐計程車去高鐵站。"),
    RegressionCase("shuttle_transfer", "如果你要去北港朝天宮，可以先搭火車到斗六再轉公車。", "若是你欲去北港朝天宮，會當先搭火車到斗六才換公車。"),
    RegressionCase("shuttle_transfer", "這班車不會進站，你要去對面月台。", "這班車袂入去站內，你欲去對面月台。"),
    RegressionCase("shuttle_transfer", "去火車站的車還有五分鐘。", "去火車頭的車閣有五分鐘。"),
    RegressionCase("shuttle_transfer", "這班車等一下會先繞去市場，再回到火車站。", "這班車等咧會先踅去市場，閣轉到火車頭。"),
    RegressionCase("shuttle_transfer", "請問高鐵接駁車多久一班？", "借問高鐵接駁車偌久一班？"),
    RegressionCase("shuttle_transfer", "請問機場接駁車多久一班？", "借問機場接駁車偌久一班？"),
    RegressionCase("shuttle_transfer", "請問高鐵接駁車從哪裡搭？", "借問高鐵接駁車對佗位搭？"),
    RegressionCase("shuttle_transfer", "請問機場接駁車從哪裡搭？", "借問機場接駁車對佗位搭？"),
    # platform / station navigation
    RegressionCase("platform_nav", "這個出口今天封閉，請改走另外一邊。", "這个出口今仔日封閉，請改走另外彼爿。"),
    RegressionCase("platform_nav", "請先看月台公告，再決定要不要上車。", "請先看月台公告，再決定敢欲上車。"),
    RegressionCase("platform_nav", "如果你要去售票口，先走到大廳再右轉。", "若是你欲去賣票口，先行到大廳再正斡。"),
    RegressionCase("platform_nav", "這個月台暫時不能上車，只能下車。", "這个月台暫時袂當上車，干焦會當落車。"),
    RegressionCase("platform_nav", "你先從電扶梯下去，再走到地下月台。", "你先對電扶梯落去，才行到地下月台。"),
    RegressionCase("platform_nav", "你先走到剪票口，再往裡面走。", "你先行到剪票口，再往內底行。"),
    RegressionCase("platform_nav", "火車站前面現在在施工，請照指標走。", "火車站頭前這馬咧施工，請照指標行。"),
    RegressionCase("platform_nav", "請在月台候車，不要跨越月台邊線。", "請佇月台等車，莫跨越月台邊線。"),
    RegressionCase("platform_nav", "往市場的車在這裡排隊。", "欲去市場的車佇遮排線。"),
    RegressionCase("platform_nav", "今天站牌移到巷口那邊。", "今仔日站牌移到巷口彼爿。"),
    RegressionCase("platform_nav", "站牌旁邊那台機器可以查時刻。", "站牌邊仔那台機器會當查時刻。"),
    RegressionCase("platform_nav", "請站在黃線後面。", "請站在黃線後壁。"),
    RegressionCase("platform_nav", "請勿在站內抽菸。", "請毋通在站內食菸。"),
    RegressionCase("platform_nav", "請勿在月台飲食。", "請毋通佇月台飲食。"),
    RegressionCase("platform_nav", "請勿在月台奔跑。", "請毋通佇月台走跳。"),
    RegressionCase("platform_nav", "請勿跨越軌道。", "請毋通跨越軌道。"),
    RegressionCase("platform_nav", "請勿倚靠車門。", "請毋通倚靠車門。"),
    RegressionCase("platform_nav", "請先讓乘客下車。", "請先讓乘客落車。"),
    RegressionCase("platform_nav", "請勿堵住車門。", "請毋通堵住車門。"),
    RegressionCase("platform_nav", "請勿在車站內奔跑。", "請毋通佇車站內走跳。"),
    RegressionCase("platform_nav", "請依序排隊上車。", "請照順序排隊上車。"),
    RegressionCase("platform_nav", "請勿在月台上吃東西。", "請毋通佇月台頂食物件。"),
    RegressionCase("platform_nav", "請勿在月台上放行李。", "請毋通佇月台頂放行李。"),
    RegressionCase("platform_nav", "請勿在月台上拍照。", "請毋通佇月台頂影相。"),
    RegressionCase("platform_nav", "請勿在站內抽菸。", "請毋通在站內食菸。"),
    RegressionCase("platform_nav", "請勿在車站內打電話。", "請毋通佇車站內講電話。"),
    RegressionCase("platform_nav", "請勿在車內打電話。", "請毋通佇車內講電話。"),
    RegressionCase("platform_nav", "請勿在車內使用手機。", "請毋通佇車內用手機。"),
    RegressionCase("platform_nav", "請勿在車內看手機。", "請毋通佇車內看手機。"),
    RegressionCase("platform_nav", "請勿將窗戶打開。", "請毋通將窗仔門拍開。"),
    RegressionCase("platform_nav", "請在右邊下車。", "請佇正手爿落車。"),
    RegressionCase("platform_nav", "可以幫我查出口位置嗎？", "會當替我查出口位置無？"),
    RegressionCase("platform_nav", "可以幫我查月台變更嗎？", "會當替我查月台變更無？"),
    RegressionCase("platform_nav", "可以幫我查轉乘月台嗎？", "會當替我查轉乘月台無？"),
    RegressionCase("platform_nav", "可以幫我查轉乘出口嗎？", "會當替我查轉乘出口無？"),
    RegressionCase("platform_nav", "可以幫我查列車月台嗎？", "會當替我查列車月台無？"),
    RegressionCase("platform_nav", "可以幫我查售票口位置嗎？", "會當替我查賣票口位置無？"),
    RegressionCase("platform_nav", "可以幫我查行李寄放處嗎？", "會當替我查行李寄放處無？"),
    RegressionCase("platform_nav", "可以幫我查驗票口位置嗎？", "會當替我查驗票口位置無？"),
    RegressionCase("platform_nav", "可以幫我查剪票口位置嗎？", "會當替我查剪票口位置無？"),
    RegressionCase("platform_nav", "可以幫我查月台位置嗎？", "會當替我查月台位置無？"),
    RegressionCase("platform_nav", "我需要查月台位置。", "我欲查月台位置。"),
    RegressionCase("platform_nav", "請協助查月台位置。", "請鬥相共查月台位置。"),
    RegressionCase("platform_nav", "我需要確認月台位置。", "我欲確認月台位置。"),
    RegressionCase("platform_nav", "我想確認月台位置。", "我想欲確認月台位置。"),
    RegressionCase("platform_nav", "可以幫我確認月台位置嗎？", "會當替我確認月台位置無？"),
    RegressionCase("platform_nav", "請幫我確認月台位置。", "請替我確認月台位置。"),
    RegressionCase("platform_nav", "麻煩你幫我確認月台位置。", "麻煩你替我確認月台位置。"),
    RegressionCase("platform_nav", "幫我確認月台位置。", "替我確認月台位置。"),
    RegressionCase("platform_nav", "請協助確認月台位置。", "請鬥相共確認月台位置。"),
    # train service / announcements
    RegressionCase("rail_service", "這一班火車大概還要等多久？", "這一班火車差不多猶愛等偌久？"),
    RegressionCase("rail_service", "這班列車只停大站，不停靠小站。", "這班列車只停大站，無停細站。"),
    RegressionCase("rail_service", "這班車延誤了，大概要晚二十分鐘。", "這班車延誤矣，差不多要慢分二十分鐘。"),
    RegressionCase("rail_service", "這班列車客滿了，麻煩你等下一班。", "這班列車客滿矣，麻煩你等後一班。"),
    RegressionCase("rail_service", "這一站今天不停靠，請到前一站下車。", "這一站今仔日無停，請到前一站落車。"),
    RegressionCase("rail_service", "這班車不會進醫院急診門口。", "這班車袂進病院急診門跤口。"),
    RegressionCase("rail_service", "你要去門診的話，在病院門口下就可以了。", "若是你欲去門診，佇病院門跤口下就會當矣。"),
    RegressionCase("rail_service", "司機休息回來就會發車。", "司機歇睏轉來就會開車。"),
    RegressionCase("rail_service", "這班車到總站就不開了。", "這班車到總站就不開矣。"),
    RegressionCase("rail_service", "司機說下一站之後要換車。", "司機講下一站了後要換車。"),
    RegressionCase("rail_service", "請問火車誤點多久？", "借問火車慢分偌久？"),
    RegressionCase("rail_service", "旅客在等你。", "旅客佇咧等你。"),
    RegressionCase("rail_service", "旅客在等候。", "旅客佇咧等候。"),
    RegressionCase("rail_service", "旅客在排隊。", "旅客佇咧排隊。"),
    # ticketing / payments
    RegressionCase("ticketing", "如果你要補票，先去窗口抽號碼牌。", "若是你欲補票，先去窗口提號碼牌。"),
    RegressionCase("ticketing", "這張票刷不過，你去櫃檯問一下。", "這張票鑢袂過，你去櫃檯問一下仔。"),
    RegressionCase("ticketing", "如果刷卡還是失敗，就先投現金。", "若是刷袂過，就先投現錢。"),
    RegressionCase("ticketing", "愛心卡今天可以正常刷卡。", "愛心卡今仔日會當正常刷卡。"),
    RegressionCase("ticketing", "老人卡感應不到的話，請你先跟司機說。", "若是老人卡感應袂著，請你先佮司機講。"),
    RegressionCase("ticketing", "你沒有零錢的話，可以去便利商店換。", "若是你無零錢，會當去便利商店換。"),
    RegressionCase("ticketing", "今天的末班車提早十分鐘開車。", "今仔日的尾班車較早十分鐘開車。"),
    RegressionCase("ticketing", "頭班車明天會晚半小時。", "頭班車明仔載會慢分半點鐘。"),
    RegressionCase("ticketing", "可以幫我查末班車時間嗎？", "會當替我查尾班車時間無？"),
    RegressionCase("ticketing", "可以幫我查車票價格嗎？", "會當替我查車票價錢無？"),
    RegressionCase("ticketing", "可以幫我查車班嗎？", "會當替我查車班無？"),
    RegressionCase("ticketing", "可以幫我查發車時間嗎？", "會當替我查開車時間無？"),
    RegressionCase("ticketing", "可以幫我查班機時間嗎？", "會當替我查班機時間無？"),
    RegressionCase("ticketing", "我想改搭下一班車。", "我想欲改搭後一班車。"),
    RegressionCase("ticketing", "可以幫我查候車時間嗎？", "會當替我查候車時間無？"),
    RegressionCase("ticketing", "我想改搭高鐵。", "我想欲改搭高鐵。"),
    RegressionCase("ticketing", "我想改搭捷運。", "我想欲改搭捷運。"),
    RegressionCase("ticketing", "可以幫我查票券效期嗎？", "會當替我查票券效期無？"),
    RegressionCase("ticketing", "我想改搭客運。", "我想欲改搭客運。"),
    RegressionCase("ticketing", "可以幫我查轉乘票價嗎？", "會當替我查轉乘票價無？"),
    RegressionCase("ticketing", "請問去高鐵站要搭哪一班？", "借問去高鐵站要搭佗一班？"),
    RegressionCase("ticketing", "請問去機場要搭哪一班？", "借問去機場要搭佗一班？"),
    RegressionCase("ticketing", "搭計程車請從前門上車。", "搭計程車請對頭前門上車。"),
    RegressionCase("ticketing", "搭計程車請從前門下車。", "搭計程車請對頭前門落車。"),
    # vehicle / onboard safety
    RegressionCase("vehicle_rules", "請勿在車內飲食。", "請毋通佇車內飲食。"),
    RegressionCase("vehicle_rules", "車輛行進時請勿走動。", "車輛行進時請毋通走動。"),
    RegressionCase("vehicle_rules", "請勿在車內大聲喧嘩。", "請毋通佇車內大聲喧嘩。"),
    RegressionCase("vehicle_rules", "請勿使用手機通話。", "請毋通用手機講電話。"),
    RegressionCase("vehicle_rules", "請勿將椅背往後倒。", "請毋通將椅背往後倒。"),
    RegressionCase("vehicle_rules", "請讓座給需要的人。", "請讓位予需要的人。"),
    RegressionCase("vehicle_rules", "請勿阻塞車道。", "請毋通阻擋車道。"),
    RegressionCase("vehicle_rules", "請勿攜帶易燃物。", "請毋通攜帶易燃物。"),
    RegressionCase("vehicle_rules", "請勿在車內抽菸。", "請毋通佇車內食菸。"),
    RegressionCase("vehicle_rules", "請勿將頭手伸出窗外。", "請毋通將頭手伸出窗外。"),
    RegressionCase("vehicle_rules", "請勿擋住走道。", "請毋通擋住走道。"),
    RegressionCase("vehicle_rules", "請勿在車內睡覺。", "請毋通佇車內睏。"),
    RegressionCase("vehicle_rules", "請將嬰兒車收好。", "請將嬰仔車收好。"),
    RegressionCase("vehicle_rules", "請將嬰兒車折疊好。", "請將嬰仔車折疊好。"),
    RegressionCase("vehicle_rules", "請勿讓嬰兒車阻塞通道。", "請毋通讓嬰仔車阻塞通道。"),
    RegressionCase("vehicle_rules", "請勿在車內播放音樂。", "請毋通佇車內播送音樂。"),
    RegressionCase("vehicle_rules", "請勿在車內化妝。", "請毋通佇車內畫妝。"),
    RegressionCase("vehicle_rules", "請勿在車內奔跑。", "請毋通佇車內浪。"),
    RegressionCase("vehicle_rules", "請勿在車內占位。", "請毋通佇車內占位。"),
    RegressionCase("vehicle_rules", "請勿坐在走道上。", "請毋通坐佇走道上。"),
    RegressionCase("accessibility_rules", "請勿占用無障礙空間。", "請毋通占用無障礙空間。"),
    RegressionCase("accessibility_rules", "請勿佔用優先席。", "請毋通佔用優先席。"),
    RegressionCase("accessibility_rules", "請先讓坐輪椅的乘客上車。", "請先讓坐輪椅的乘客上車。"),
    RegressionCase("accessibility_rules", "請勿讓行李放在座位上。", "請毋通讓行李囥佇位仔頂。"),
    RegressionCase("accessibility_rules", "請勿站在門口。", "請毋通站佇門跤口。"),
    RegressionCase("accessibility_rules", "請給輪椅用者優先。", "請給輪椅用者優先。"),
    RegressionCase("accessibility_rules", "請勿將腳放在座位上。", "請毋通將腳囥佇位仔頂。"),
    RegressionCase("accessibility_rules", "請勿在車內看書。", "請毋通佇車內看冊。"),
    RegressionCase("accessibility_rules", "請勿在車內褪鞋。", "請毋通佇車內褪鞋。"),
    RegressionCase("accessibility_rules", "請勿佔用輪椅區。", "請毋通佔用輪椅區。"),
    RegressionCase("vehicle_rules", "請勿在車內咳嗽。", "請毋通佇車內呿呿嗽。"),
    RegressionCase("vehicle_rules", "請勿在車內打噴嚏。", "請毋通佇車內拍咳啾。"),
    RegressionCase("vehicle_rules", "請勿在車內脫口罩。", "請毋通佇車內脫喙罨。"),
    RegressionCase("vehicle_rules", "請勿在車內飲水。", "請毋通佇車內飲水。"),
    RegressionCase("vehicle_rules", "請勿在車內吸煙。", "請毋通佇車內食菸。"),
    RegressionCase("vehicle_rules", "請勿在車內吐痰。", "請毋通佇車內呸痰。"),
    RegressionCase("vehicle_rules", "請勿在車內丟垃圾。", "請毋通佇車內丟糞埽。"),
    RegressionCase("vehicle_rules", "請勿在車內吃檳榔。", "請毋通佇車內食菁仔。"),
    RegressionCase("vehicle_rules", "請勿在車內嘔吐。", "請毋通佇車內吐。"),
    RegressionCase("vehicle_rules", "請勿在車內使用雨傘。", "請毋通佇車內用雨傘。"),
    RegressionCase("platform_rules", "請勿在月台上打電話。", "請毋通佇月台頂講電話。"),
    RegressionCase("platform_rules", "請勿在月台上喝飲料。", "請毋通佇月台頂啉飲料。"),
    RegressionCase("platform_rules", "請勿在月台上聊天。", "請毋通佇月台頂開講。"),
    RegressionCase("platform_rules", "請勿在月台上躺下。", "請毋通佇月台頂躺下。"),
    RegressionCase("platform_rules", "請勿在車站內吸菸。", "請毋通佇車站內食菸。"),
    RegressionCase("platform_rules", "請勿在車站內喝水。", "請毋通佇車站內啉水。"),
    RegressionCase("platform_rules", "請勿在車站內看手機。", "請毋通佇車站內看手機。"),
    RegressionCase("platform_rules", "請勿亂丟垃圾。", "請毋通亂丟糞埽。"),
    RegressionCase("platform_rules", "請勿在月台上抽菸。", "請毋通佇月台頂食菸。"),
    RegressionCase("platform_rules", "請勿在車站內丟垃圾。", "請毋通佇車站內丟糞埽。"),
    RegressionCase("platform_rules", "請勿在月台上大聲說話。", "請毋通佇月台頂喧。"),
    RegressionCase("platform_rules", "請勿在車站內大聲說話。", "請毋通佇車站內喧。"),
    RegressionCase("platform_rules", "請勿在月台上推擠。", "請毋通佇月台頂推擠。"),
    RegressionCase("platform_rules", "請勿在車站內推擠。", "請毋通佇車站內推擠。"),
    RegressionCase("platform_rules", "請勿在月台上奔跑。", "請毋通佇月台頂浪。"),
    RegressionCase("platform_rules", "請勿在車站內奔跑。", "請毋通佇車站內走跳。"),
    RegressionCase("platform_rules", "請勿在月台上聊天。", "請毋通佇月台頂開講。"),
    RegressionCase("platform_rules", "請勿在車站內聊天。", "請毋通佇車站內開講。"),
    RegressionCase("platform_rules", "請勿在月台上大聲喧嘩。", "請毋通佇月台頂昂聲噓嚇叫。"),
    RegressionCase("platform_rules", "請勿在車站內大聲喧嘩。", "請毋通佇車站內昂聲噓嚇叫。"),
    # queue / boarding
    RegressionCase("queue_rules", "請勿插隊。", "請毋通插隊。"),
    RegressionCase("queue_rules", "請保持距離。", "請保持距離。"),
    RegressionCase("queue_rules", "請先下後上。", "請先落車後上車。"),
    RegressionCase("queue_rules", "請勿在月台邊線後等待。", "請毋通佇月台邊線後待。"),
    RegressionCase("queue_rules", "請勿在月台前排隊。", "請毋通佇月台前排隊。"),
    RegressionCase("queue_rules", "請在月台後面排隊。", "請佇月台後壁排隊。"),
    RegressionCase("queue_rules", "請先讓乘客下車。", "請先讓乘客落車。"),
    RegressionCase("queue_rules", "請勿先上車。", "請毋通先上車。"),
    RegressionCase("queue_rules", "請勿在車站內等候。", "請毋通佇車站內等候。"),
    RegressionCase("queue_rules", "請勿在月台上等候。", "請毋通佇月台頂等候。"),
    # ticketing / station service
    RegressionCase("ticketing_rules", "請勿在車站內換票。", "請毋通佇車站內換票。"),
    RegressionCase("ticketing_rules", "請勿在車站內補票。", "請毋通佇車站內補票。"),
    RegressionCase("ticketing_rules", "請勿在月台上補票。", "請毋通佇月台頂補票。"),
    RegressionCase("ticketing_rules", "請勿在車內補票。", "請毋通佇車內補票。"),
    RegressionCase("ticketing_rules", "請勿在車站內查詢班次。", "請毋通佇車站內查詢班次。"),
    RegressionCase("ticketing_rules", "請勿在車站內查詢票價。", "請毋通佇車站內查詢票價。"),
    RegressionCase("ticketing_rules", "請勿在車站內查詢時刻。", "請毋通佇車站內查詢時刻。"),
    RegressionCase("ticketing_rules", "請勿在月台上查詢票價。", "請毋通佇月台頂查詢票價。"),
    RegressionCase("ticketing_rules", "請勿在月台上查詢時刻。", "請毋通佇月台頂查詢時刻。"),
    RegressionCase("ticketing_rules", "請勿在月台上辦理手續。", "請毋通佇月台頂辦理手續。"),
    # station inquiry / service desk
    RegressionCase("station_inquiry", "請勿在車站內問路。", "請毋通佇車站內問路。"),
    RegressionCase("station_inquiry", "請勿在車站內問時間。", "請毋通佇車站內問時間。"),
    RegressionCase("station_inquiry", "請勿在車站內問票價。", "請毋通佇車站內問票價。"),
    RegressionCase("station_inquiry", "請勿在車站內問月台。", "請毋通佇車站內問月台。"),
    RegressionCase("station_inquiry", "請勿在車站內討論路線。", "請毋通佇車站內討論路線。"),
    RegressionCase("station_inquiry", "請勿在車站內討論班次。", "請毋通佇車站內討論班次。"),
    RegressionCase("station_inquiry", "請勿在月台上問方向。", "請毋通佇月台頂問方向。"),
    RegressionCase("station_inquiry", "請勿在月台上問時間。", "請毋通佇月台頂問時間。"),
    RegressionCase("station_inquiry", "請勿在車站內找服務台。", "請毋通佇車站內找服務台。"),
    RegressionCase("station_inquiry", "請勿在月台上找服務台。", "請毋通佇月台頂找服務台。"),
    RegressionCase("station_inquiry", "請勿在車站內問售票口。", "請毋通佇車站內問賣票口。"),
    RegressionCase("station_inquiry", "請勿在月台上問售票口。", "請毋通佇月台頂問賣票口。"),
    RegressionCase("station_inquiry", "請勿在車站內詢問售票口。", "請毋通佇車站內詢問賣票口。"),
    RegressionCase("station_inquiry", "請勿在月台上詢問售票口。", "請毋通佇月台頂詢問賣票口。"),
    RegressionCase("station_inquiry", "請勿在車站內找售票口。", "請毋通佇車站內找賣票口。"),
    RegressionCase("station_inquiry", "請勿在月台上找售票口。", "請毋通佇月台頂找賣票口。"),
    RegressionCase("station_inquiry", "請勿在車站內問服務人員。", "請毋通佇車站內問服務人員。"),
    RegressionCase("station_inquiry", "請勿在月台上問服務人員。", "請毋通佇月台頂問服務人員。"),
    RegressionCase("station_inquiry", "請勿在車站內詢問服務人員。", "請毋通佇車站內詢問服務人員。"),
    RegressionCase("station_inquiry", "請勿在月台上詢問服務人員。", "請毋通佇月台頂詢問服務人員。"),
    RegressionCase("station_gate_inquiry", "請勿在車站內問出口。", "請毋通佇車站內問出口。"),
    RegressionCase("station_gate_inquiry", "請勿在月台上問出口。", "請毋通佇月台頂問出口。"),
    RegressionCase("station_gate_inquiry", "請勿在車站內詢問出口。", "請毋通佇車站內詢問出口。"),
    RegressionCase("station_gate_inquiry", "請勿在月台上詢問出口。", "請毋通佇月台頂詢問出口。"),
    RegressionCase("station_gate_inquiry", "請勿在車站內找出口。", "請毋通佇車站內揣出口。"),
    RegressionCase("station_gate_inquiry", "請勿在月台上找出口。", "請毋通佇月台頂揣出口。"),
    RegressionCase("station_gate_inquiry", "請勿在車站內問剪票口。", "請毋通佇車站內問剪票口。"),
    RegressionCase("station_gate_inquiry", "請勿在月台上問剪票口。", "請毋通佇月台頂問剪票口。"),
    RegressionCase("station_gate_inquiry", "請勿在車站內問驗票口。", "請毋通佇車站內問驗票口。"),
    RegressionCase("station_gate_inquiry", "請勿在月台上問驗票口。", "請毋通佇月台頂問驗票口。"),
    RegressionCase("station_facility_inquiry", "請勿在車站內找候車室。", "請毋通佇車站內揣等車室。"),
    RegressionCase("station_facility_inquiry", "請勿在月台上找候車室。", "請毋通佇月台頂揣等車室。"),
    RegressionCase("station_facility_inquiry", "請勿在車站內問候車室。", "請毋通佇車站內問等車室。"),
    RegressionCase("station_facility_inquiry", "請勿在月台上問候車室。", "請毋通佇月台頂問等車室。"),
    RegressionCase("station_facility_inquiry", "請勿在車站內找行李寄放處。", "請毋通佇車站內揣行李寄放處。"),
    RegressionCase("station_facility_inquiry", "請勿在月台上找行李寄放處。", "請毋通佇月台頂揣行李寄放處。"),
    RegressionCase("station_facility_inquiry", "請勿在車站內問服務櫃檯。", "請毋通佇車站內問服務櫃檯。"),
    RegressionCase("station_facility_inquiry", "請勿在月台上問服務櫃檯。", "請毋通佇月台頂問服務櫃檯。"),
    RegressionCase("station_facility_inquiry", "請勿在車站內問洗手間。", "請毋通佇車站內問便所。"),
    RegressionCase("station_facility_inquiry", "請勿在月台上問洗手間。", "請毋通佇月台頂問便所。"),
    # service / redirect / lost property
    RegressionCase("service_redirect", "如果你只是問廁所在哪裡，我可以跟你說。", "若是你只是問便所佇佗位，我會當共你講。"),
    RegressionCase("service_redirect", "這個問題不是站務能決定的，你要問服務台。", "這个問題毋是站務會當決定的，你欲問服務台。"),
    RegressionCase("service_redirect", "這個問題跟公車無關，我沒辦法回答。", "這个問題佮公車無關，我無法度回答。"),
    RegressionCase("service_redirect", "如果你要找失物，我可以幫你轉給總站。", "若是你欲找失物，我會當替你轉去總站。"),
    RegressionCase("service_redirect", "如果你要找失物，我先幫你記車牌。", "若是你欲找失物，我先替你記車牌。"),
    RegressionCase("service_redirect", "失物要送回總站，你下午再打電話確認。", "遺失物愛送轉去總站，你下晝閣敲電話確認。"),
    RegressionCase("service_redirect", "這個不是公車問題，請去問警察。", "這个毋是公車問題，請去問警察。"),
    RegressionCase("service_redirect", "可以幫我查轉乘路線嗎？", "會當替我查轉乘路線無？"),
    RegressionCase("service_redirect", "可以幫我查轉乘時間嗎？", "會當替我查轉乘時間無？"),
    RegressionCase("service_redirect", "這班車會停哪幾站？", "這班車會停佗幾站？"),
    RegressionCase("service_redirect", "可以幫我查月台嗎？", "會當替我查月台無？"),
    RegressionCase("service_redirect", "可以幫我找服務台嗎？", "會當替我揣服務台無？"),
    RegressionCase("service_redirect", "可以幫我改下車站嗎？", "會當替我改落車站無？"),
    RegressionCase("service_redirect", "請協助改下車站。", "請鬥相共改落車站。"),
    RegressionCase("service_redirect", "可以幫我查轉乘站嗎？", "會當替我查轉乘站無？"),
    RegressionCase("service_redirect", "可以幫乘客確認班次嗎？", "會當替乘客確認班次無？"),
    RegressionCase("service_redirect", "可不可以幫乘客換位子？", "敢會當替乘客換位子？"),
    RegressionCase("service_redirect", "麻煩協助乘客上車。", "麻煩鬥相共乘客上車。"),
    RegressionCase("service_redirect", "可以幫旅客確認班次嗎？", "會當替旅客確認班次無？"),
    RegressionCase("service_redirect", "可不可以幫旅客換位子？", "敢會當替旅客換位子？"),
    RegressionCase("service_redirect", "麻煩協助旅客上車。", "麻煩鬥相共旅客上車。"),
    RegressionCase("service_redirect", "可以幫站務員換班嗎？", "會當替站務員換班無？"),
    RegressionCase("service_redirect", "可不可以幫站務員換班？", "敢會當替站務員換班？"),
    RegressionCase("service_redirect", "請協助站務員換班。", "請鬥相共站務員換班。"),
    RegressionCase("service_redirect", "可以幫警察換班嗎？", "會當替警察換班無？"),
    RegressionCase("service_redirect", "可不可以幫警察換班？", "敢會當替警察換班？"),
    RegressionCase("service_redirect", "請協助警察換班。", "請鬥相共警察換班。"),
    RegressionCase("service_redirect", "可以幫司機換班嗎？", "會當替司機換班無？"),
    RegressionCase("service_redirect", "可不可以幫司機換班？", "敢會當替司機換班？"),
    RegressionCase("service_redirect", "請協助司機換班。", "請鬥相共司機換班。"),
    # crowd / safety / queue
    RegressionCase("crowd_safety", "今天車站人很多，你先到旁邊等一下。", "今仔日車站人誠濟，你先到邊仔等一下。"),
    RegressionCase("crowd_safety", "這裡不能停車接人，請到外圍等。", "遮袂當停車接人，請到外圍等。"),
    RegressionCase("crowd_safety", "今天雨很大，車班可能不穩定。", "今仔日雨真大，車班可能不穩定。"),
    RegressionCase("crowd_safety", "請不要站在黃線外面。", "請莫徛在黃線外口。"),
    RegressionCase("crowd_safety", "這裡現在只下車不上車。", "遮這馬干焦落車，無上車。"),
    RegressionCase("crowd_safety", "請不要把行李放在走道上。", "請莫共行李囥佇走道上。"),
    RegressionCase("crowd_safety", "上車請往後面移動。", "上車請往後壁移動。"),
    RegressionCase("crowd_safety", "請讓老人家先上車。", "請讓老大人先上車。"),
    RegressionCase("crowd_safety", "人很多的時候，請排隊不要插隊。", "人濟的時陣，請排隊莫插隊。"),
    RegressionCase("crowd_safety", "請不要靠近月台邊緣。", "請莫靠近月台邊仔。"),
    # hospital / campus / specific destination
    RegressionCase("destinations", "如果你要去醫院，這班車不會進病院內底。", "若是你欲去病院，這班車袂進病院內底。"),
    RegressionCase("destinations", "這班車今天不停靠學校門口。", "這班車今仔日無停學校門跤口。"),
    RegressionCase("destinations", "如果你要去學校裡面，要在校門口下車再走進去。", "若是你欲去學校內底，要在校門跤口落車才行進去。"),
    RegressionCase("destinations", "如果你要去夜市，在圓環那站下車就好。", "若是你欲去夜市，在圓環那站落車就好。"),
    RegressionCase("destinations", "去動物園的車一天只有兩班，你要注意時間。", "去動物園的車一工只有兩班，你欲注意時間。"),
    RegressionCase("destinations", "如果你要去老街，我幫你確認班次。", "若是你欲去老街，我替你確認班次。"),
    RegressionCase("destinations", "這班車最遠只到海邊，不進市區。", "這班車上遠只到海墘，不進市區。"),
    RegressionCase("destinations", "如果你要去文化館，在前一站下車再走進去。", "若是你欲去文化館，在前一站落車才行進去。"),
]


def main() -> int:
    return run_regression_cli(
        TRANSPORT_REGRESSION_CASES,
        description='非公車交通情境 regression runner',
    )


if __name__ == "__main__":
    raise SystemExit(main())
